language: node_js
node_js:
  - "8.9"
  - "9.11.1"
cache:
  directories:
    - node_modules
before_install:
  - npm install -g npm@6.1.0
script:
  - npm audit
  - npm test
after_script: "npm install coveralls@^2.13.3 && cat ./coverage/lcov.info | coveralls"